site_name: MkDocs Test Site
theme:
#  name: bootstrap386
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
  palette:
    scheme: default
    primary: blue
    accent: blue
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
